- id: "local"
- id: "uniform"
  flip_probability: 0.5
- id: "quantum"
  max_chi: 32
  max_belief_propagation_iterations: 100
  layers_per_regauging: 1
  gamma: 0.1
  time_step_per_layer: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, ]
  accuracy: 1e-5
  synchronous_update: False
  traversal_type: "dfs"