time_limit: 100
heuristics:
  # maxcut heuristics
  - BASELINE
  - BURER2002
  - DESOUSA2013
  - DUARTE2005
  - FESTA2002G
  - FESTA2002GPR
  - FESTA2002GVNS
  - FESTA2002GVNSPR
  - FESTA2002VNS
  - FESTA2002VNSPR
  - LAGUNA2009CE
  - LAGUNA2009HCE
  # QUBO heuristics
  - ALKHAMIS1998
  - BEASLEY1998SA
  - BEASLEY1998TS
  - GLOVER1998a
  - GLOVER2010
  - HASAN2000GA
  - HASAN2000TS
  - KATAYAMA2000
  - KATAYAMA2001
  - LODI1999
  - LU2010
  - MERZ1999CROSS
  - MERZ1999GLS
  - MERZ1999MUTATE
  - MERZ2002GREEDY
  - MERZ2002GREEDYKOPT
  - MERZ2002KOPT
  - MERZ2002ONEOPT
  - MERZ2004
  - PALUBECKIS2004bMST1
  - PALUBECKIS2004bMST2
  - PALUBECKIS2004bMST3
  - PALUBECKIS2004bMST4
  - PALUBECKIS2004bMST5
  - PALUBECKIS2004bSTS
  - PALUBECKIS2006
  - PARDALOS2008
