name: Running dequantizer validation script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jax["cpu"] numpy pytest mypy black pylint
    - name: Run validation script
      run: |
        chmod +x ./ci/validate.sh
        ./ci/validate.sh
      shell: bash
